baseURL: /
theme: hugo-apero
languageCode: en
title: Andrew Leach
author: Andrew Leach
copyright: ''
googleAnalytics: ''
disqusShortname: ''
metaDataFormat: yaml
footnoteReturnLinkContents: '&#8617;'
paginate: 5
preserveTaxonomyNames: yes
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
enableEmoji: yes
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      hardwraps: no
      unsafe: yes
  highlight:
    style: github
  tableOfContents:
    endLevel: 2
    ordered: no
    startLevel: 2
params:
  custom_theme: ''
  customheadingFontFamily: EB Garamond
  customtextFontFamily: EB Garamond
  description: Energy and Environmental Economist
  favicon: /img/favicon.ico
  headingFontFamily: sans-serif
  logo: /img/logo_capture.PNG
  mainSections:
    - blog
    - publications
    - project
    - opinion
  navallcaps: yes
  orgLocal: Edmonton, AB
  orgName: Andrew Leach
  social:
    - icon: github
      icon_pack: fab
      url: https://github.com/leachandrew
    - icon: instagram
      icon_pack: fab
      url: https://www.instagram.com/not_andy_leach
    - icon: twitter
      icon_pack: fab
      url: https://twitter.com/andrew_leach
    - icon: orcid
      icon_pack: ai
      url: https://orcid.org/0000-0003-1823-3876
    - icon: rss
      icon_pack: fas
      url: /blog/index.xml
  socialInFooter: yes
  socialInHeader: no
  textFontFamily: sans-serif
  theme: grayscale
  twitter: andrew_leach
  utterances:
    issue_term: pathname
    label: 'comments :crystal_ball:'
    repo_name: leachandrew
    theme: boxy-light
    use_utterances: yes
taxonomies:
  category: categories
  series: series
  tag: tags
menu:
  footer:
    - name: License
      title: License
      url: /license/
      weight: 1
    - name: Contact
      title: Contact form
      url: /contact/
      weight: 2
  header:
    - name: About
      title: About Andrew Leach
      url: /about/
      weight: 1
    - name: Blog
      title: Blog
      url: http://andrewleach.ca
      weight: 2
    - name: Publications
      title: Academic Publications
      url: /publications/
      weight: 3
    - name: Projects
      title: Project Portfolio
      url: /project/
      weight: 4
    - name: Opinion
      title: Opinion
      url: /opinion/
      weight: 6
privacy:
  disqus:
    disable: no
  googleAnalytics:
    anonymizeIP: yes
    disable: no
    respectDoNotTrack: yes
  instagram:
    disable: no
    simple: yes
  twitter:
    disable: no
    enableDNT: yes
    simple: no
  vimeo:
    disable: no
    enableDNT: yes
    simple: yes
  youtube:
    disable: no
    privacyEnhanced: yes
